version: '3.8'
services:
  backend:
    build: ./backend
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - .env.example
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    env_file:
      - .env.example
